services:
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=medialib
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  web:
    build: .
    command: gunicorn medialib_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DB_NAME=medialib
      - DB_USER=user
      - DB_PASS=password
      - DB_HOST=db
      - DB_PORT=5432

volumes:
  postgres_data: